environment:
  matrix:
    - nodejs_version: "6.10"
    - nodejs_version: "8.1"
cache:
  - node_modules
install:
  - ps: Install-Product node $env:nodejs_version
  - npm config set shrinkwrap false
  - if exist node_modules npm prune
  - if exist node_modules npm rebuild
  - npm install
  - npm install -g grunt-cli
build: off
test_script:
  - node --version
  - npm --version
  - grunt ci
version: "{build}"
