sudo: false
language: node_js
node_js:
  - 10
cache:
  directories:
    - node_modules
before_install:
  - npm i -g npm@6.12
script: npm run build && npm test
deploy:
  skip_cleanup: true
  provider: script
  script: ./node_modules/.bin/codecov
  on:
    branch: master
