sudo: false
language: node_js
node_js:
  - 12
cache:
  directories:
    - node_modules
script: npm run ci
deploy:
  skip_cleanup: true
  provider: script
  script: ./node_modules/.bin/codecov
  on:
    branch: master
