sudo: false
language: node_js
node_js:
  - 6
cache:
  directories:
    - node_modules
before_install:
    - npm install -g grunt-cli
script: grunt ci
deploy:
  skip_cleanup: true
  provider: script
  script: ./node_modules/.bin/codecov
  on:
    branch: master
